# Generated by Django 5.0.7 on 2024-07-13 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.CharField(choices=[('B', 'Baixo'), ('M', 'Médio'), ('A', 'Alto')], default='B', max_length=1)),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='central.roadmap')),
                ('stack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='central.stack')),
            ],
        ),
    ]
