# Generated by Django 5.0.7 on 2024-07-13 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0002_conjunto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('doc_1', models.CharField(max_length=100)),
                ('doc_2', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('nasc', models.CharField(max_length=100)),
                ('bc', models.CharField(max_length=100)),
                ('ag', models.CharField(max_length=100)),
                ('cc', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='conjunto',
            name='roadmap',
        ),
        migrations.RemoveField(
            model_name='conjunto',
            name='stack',
        ),
        migrations.DeleteModel(
            name='Roadmap',
        ),
        migrations.DeleteModel(
            name='Conjunto',
        ),
        migrations.DeleteModel(
            name='Stack',
        ),
    ]
