# Generated by Django 5.0.7 on 2024-07-13 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0004_rename_doc_1_cliente_cpf_rename_doc_2_cliente_rg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='ag',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='bc',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cc',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nasc',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rg',
            field=models.CharField(max_length=9),
        ),
    ]
