# Generated by Django 5.0.7 on 2024-07-13 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0006_cliente_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='ag',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='bc',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cc',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tel',
            field=models.CharField(max_length=13),
        ),
    ]
