# Generated by Django 5.0.7 on 2024-07-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0007_alter_cliente_ag_alter_cliente_bc_alter_cliente_cc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='file_pdf',
            field=models.FileField(blank=True, default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='cliente',
            name='foto',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nasc',
            field=models.DateField(),
        ),
    ]
